### ISSUE TITLE
Upgrade to Kotlin 1.4

### ISSUE THREAD

**Issue by plastiv** [autonomousapps/dependency-analysis-android-gradle-plugin#333]
Running plugin on a project with 1.4.20 kotlin results in an error

```stacktrace
Caught an exception trying to connect to Kotlin Daemon:
java.lang.NoSuchMethodError: org.jetbrains.kotlin.cli.common.messages.MessageCollector$DefaultImpls.report$default(Lorg/jetbrains/kotlin/cli/common/messages/MessageCollector;Lorg/jetbrains/kotlin/cli/common/messages/CompilerMessageSeverity;Ljava/lang/String;Lorg/jetbrains/kotlin/cli/common/messages/CompilerMessageSourceLocation;ILjava/lang/Object;)V
        at org.jetbrains.kotlin.compilerRunner.KotlinCompilerRunnerUtils.newDaemonConnection(KotlinCompilerRunnerUtils.kt:83)
        at org.jetbrains.kotlin.compilerRunner.KotlinCompilerRunnerUtils.newDaemonConnection$default(KotlinCompilerRunnerUtils.kt:49)
        at org.jetbrains.kotlin.compilerRunner.GradleCompilerRunner$Companion.getDaemonConnectionImpl$kotlin_gradle_plugin(GradleKotlinCompilerRunner.kt:187)
        at org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork.compileWithDaemon(GradleKotlinCompilerWork.kt:165)
        at org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork.compileWithDaemonOrFallbackImpl(GradleKotlinCompilerWork.kt:141)
        at org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork.run(GradleKotlinCompilerWork.kt:124)
        at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:57)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:67)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:63)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:63)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
        at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:60)
        at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:200)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:748)

Could not perform incremental compilation: Could not connect to Kotlin compile daemon
Could not connect to kotlin daemon. Using fallback strategy.
```

Running compilation without kotlin daemon results in a major performance slowdown. Is there any blocker for 1.4 upgrade?

**Comment by autonomousapps** [comment]
Are you able to provide a minimal reproducer? That would help me see
what the issue is precisely and if there's anything I can do to
mitigate. 

I am avoiding migrating to 1.4 until Gradle 7 because this is a Gradle

plugin and 1.3 is the default. I basically don't want to deal with the

compatibility issues. 

On November 28, 2020, GitHub <notifications@github.com> wrote:
> Running plugin on a project with 1.4.20 kotlin results in an error
>
> Caught an exception trying to connect to Kotlin Daemon:
> java.lang.NoSuchMethodError:
> org.jetbrains.kotlin.cli.common.messages.MessageCollector$DefaultImpls.report$default(Lorg/jetbrains/kotlin/cli/common/messages/MessageCollector;Lorg/jetbrains/kotlin/cli/common/messages/CompilerMessageSeverity;Ljava/lang/String;Lorg/jetbrains/kotlin/cli/common/messages/CompilerMessageSourceLocation;ILjava/lang/Object;)V
> at
> org.jetbrains.kotlin.compilerRunner.KotlinCompilerRunnerUtils.newDaemonConnection(KotlinCompilerRunnerUtils.kt:83)
> at
> org.jetbrains.kotlin.compilerRunner.KotlinCompilerRunnerUtils.newDaemonConnection$default(KotlinCompilerRunnerUtils.kt:49)
> at
> org.jetbrains.kotlin.compilerRunner.GradleCompilerRunner$Companion.getDaemonConnectionImpl$kotlin_gradle_plugin(GradleKotlinCompilerRunner.kt:187)
> at
> org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork.compileWithDaemon(GradleKotlinCompilerWork.kt:165)
> at
> org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork.compileWithDaemonOrFallbackImpl(GradleKotlinCompilerWork.kt:141)
> at
> org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork.run(GradleKotlinCompilerWork.kt:124)
> at
> org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:57)
> at
> org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
> at
> org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:67)
> at
> org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:63)
> at
> org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
> at
> org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:63)
> at
> org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
> at
> org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
> at
> org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
> at
> org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
> at
> org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
> at
> org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
> at
> org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
> at
> org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
> at
> org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
> at
> org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
> at
> org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
> at
> org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
> at
> org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
> at
> org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:60)
> at
> org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:200)
> at java.util.concurrent.FutureTask.run(FutureTask.java:266) at
> org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
> at
> org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
> at
> org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
> at
> java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> at java.util.concurrent.FutureTask.run(FutureTask.java:266) at
> org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
> at
> org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
> at
> java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> at
> java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> at
> org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
> at java.lang.Thread.run(Thread.java:748) Could not perform incremental

> compilation: Could not connect to Kotlin compile daemon Could not
> connect to kotlin daemon. Using fallback strategy.
> Running compilation without kotlin daemon results in a major
> performance slowdown. Is there any blocker for 1.4 upgrade?
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/autonomousapps/dependency-analysis-android-gradle-

plugin/issues/333>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABJG5POMHHX7RVKB3SWXSG3SSJO6PANCNFSM4UGR47FQ>.

**Comment by plastiv** [comment]
Thank you for a quick response! I didn't had on top of my mind that gradle injects bundled kotlin (for kts) into plugins classpath. Seems like a valid reason, I shall wait then 👍 

I think just using a project with latest android and latest kotlin will trigger an issue, will see if I can make a repro case based on integration tests at the repo.

**Comment by bvschaik** [comment]
I'm also encountering this error. Version 0.66.0 introduced it, 0.65.0 and lower are unaffected. My project has been using Kotlin 1.4.20 for a while already in combination with 0.63.0 of this plugin so I'm not sure that the Kotlin version is to blame.

Minimum reproducing example:

1. Use Android Studio 4.1.1
1. Create a new project, use Kotlin (you'll get 1.4.20 by default), minimum api level 21, I chose "no activity"
1. Add plugin to root `build.gradle`:
    ```
    ...
    buildscript {
        ...
        dependencies {
            ...
            classpath "com.autonomousapps:dependency-analysis-gradle-plugin:0.66.0"
        }
    }
    apply plugin: "com.autonomousapps.dependency-analysis"
    ...
    ```
1. Run `./gradlew testDebugUnitTest` from the command line and note the error reported in the issue scroll by.
1. Downgrade to 0.65.0 of the plugin, run again and note the error is gone

**Comment by autonomousapps** [comment]
Thank you, that's super helpful. 

On December 1, 2020, GitHub <notifications@github.com> wrote:
> I'm also encountering this error. Version 0.66.0 introduced it, 0.65.0

> and lower are unaffected. My project has been using Kotlin 1.4.20 for

> a while already in combination with 0.63.0 of this plugin so I'm not

> sure that the Kotlin version is to blame.
>
> Minimum reproducing example:
>
> 1. Use Android Studio 4.1.1
> 2. Create a new project, use Kotlin (you'll get 1.4.20 by default),
>    minimum api level 21, I chose "no activity"
> 3. Add plugin to root build.gradle: 
> 4. ... buildscript { ... dependencies { ... classpath
>    "com.autonomousapps:dependency-analysis-gradle-plugin:0.66.0" } }

>    apply plugin: "com.autonomousapps.dependency-analysis" ...
> 5. Run ./gradlew testDebugUnitTest from the command line and note the

>    error reported in the issue scroll by.
> 6. Downgrade to 0.65.0 of the plugin, run again and note the error is

>    gone
>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/autonomousapps/dependency-analysis-android-gradle-

plugin/issues/333#issuecomment-737232301>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABJG5PIWTU3LEVZYEM2J23TSSY6ZBANCNFSM4UGR47FQ>.

**Comment by autonomousapps** [comment]
Assuming this builds fine on CI, I will release v0.69.0 soon which will resolve this issue.
