### ISSUE TITLE
ComputeUsagesTask fails with "items must not be empty"

### ISSUE THREAD

**Issue by loetifuss** [autonomousapps/dependency-analysis-android-gradle-plugin#780]
**Plugin version**
1.13.1

**Gradle version**
7.4.2

**(Optional) Android Gradle Plugin (AGP) version**
n.a.

**Describe the bug**
After moving to the latest plugin version (1.13.1) analysis fails with the following error;

```
Caused by: org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing com.autonomousapps.tasks.ComputeUsagesTask$ComputeUsagesAction	
at org.gradle.workers.internal.DefaultWorkerExecutor$WorkItemExecution.waitForCompletion(DefaultWorkerExecutor.java:339)	
...
Caused by: java.lang.IllegalStateException: items must not be empty	
at com.autonomousapps.model.intermediates.ReasonKt.buildReason(Reason.kt:233)	
at com.autonomousapps.model.intermediates.ReasonKt.access$buildReason(Reason.kt:1)	
at com.autonomousapps.model.intermediates.Reason$ServiceLoader.<init>(Reason.kt:205)	
at com.autonomousapps.tasks.GraphVisitor.visit(ComputeUsagesTask.kt:172)	
at com.autonomousapps.visitor.GraphViewReader.accept(GraphViewReader.kt:18)	
at com.autonomousapps.tasks.ComputeUsagesTask$ComputeUsagesAction.execute(ComputeUsagesTask.kt:92)	
at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)	
at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)	
at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)	
at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)	
at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)	
at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)	
at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)	
at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)	
at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)	
at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)	
at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)	
at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)	
at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)	
at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)	
at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)	
at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)	
at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)	
at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:205)	
at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:187)	
at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.access$700(DefaultConditionalExecutionQueue.java:120)	
at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner$1.run(DefaultConditionalExecutionQueue.java:162)	
at org.gradle.internal.Factories$1.create(Factories.java:31)
```

**To Reproduce**
1. Use plugin version > 1.8.0
2. Execute task "projectHealth" for any sub-project in the build
3. Analysis fails in 'ComputeUsagesTask'

**Expected behavior**
analysis should not fail

**Additional context**
Dependency Analysis Plugin is used in a large multi-module Gradle build. The error only occurs with any plugin version > 1.8.0.

**Comment by autonomousapps** [comment]
Thanks for the report!

**Comment by autonomousapps** [comment]
> Execute task "projectHealth" for any sub-project in the build

Do you have a reproducer?

**Comment by autonomousapps** [comment]
@loetifuss would you be willing to try a snapshot for debugging purposes? I can fix this, but I'm confused how it's happening in the first place. Ideally I'll add some extra logging for you to run on your project (or you could provide a reproducer). Thanks.

**Comment by loetifuss** [comment]
> @loetifuss would you be willing to try a snapshot for debugging purposes? I can fix this, but I'm confused how it's happening in the first place. Ideally I'll add some extra logging for you to run on your project (or you could provide a reproducer). Thanks.

@autonomousapps Sure, I can try a snapshot,.

**Comment by autonomousapps** [comment]
@loetifuss thanks! If you use the latest snapshot (`1.13.2-SNAPSHOT`) (see [here](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/wiki/Adding-to-your-project) for how to add a snapshot), you can then enable debug logging in your build and look for logs like [this](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/src/main/kotlin/com/autonomousapps/tasks/FindServiceLoadersTask.kt#L89-L92). You can enable debug logging with `-d`, e.g., `./gradlew buildHealth -d`.

**Comment by loetifuss** [comment]
> @loetifuss thanks! If you use the latest snapshot (`1.13.2-SNAPSHOT`) (see [here](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/wiki/Adding-to-your-project) for how to add a snapshot), you can then enable debug logging in your build and look for logs like [this](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/src/main/kotlin/com/autonomousapps/tasks/FindServiceLoadersTask.kt#L89-L92). You can enable debug logging with `-d`, e.g., `./gradlew buildHealth -d`.

@autonomousapps 
It works using the latest snapshot! The culprit seems to be the JAR file "net.sourceforge.pmd.pmd-core-6.17.0.jar" containing empty service loader definition files. Here is the output of debug logging:

`2022-09-20T16:17:35.692+0200 [DEBUG] [org.gradle.api.Task] net.sourceforge.pmd.pmd-core-6.17.0.jar has a services file at path META-INF/services/net.sourceforge.pmd.cpd.Language, but there are no services! File contents:
<<>>`
