### ISSUE TITLE
NullPointerException when executing explodeXmlSourceDebug

### ISSUE THREAD

**Issue by SimonMarquis** [autonomousapps/dependency-analysis-android-gradle-plugin#826]
**Plugin version**
1.16.0

**Gradle version**
7.6

**(Optional) Android Gradle Plugin (AGP) version**
7.3.1

**Describe the bug**
When running the tasks `buildHealth printDuplicateDependencies --stacktrace` on a large codebase, we encounter this NPE:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':[MyModule]:explodeXmlSourceDebug'.
> A failure occurred while executing com.autonomousapps.tasks.XmlSourceExploderTask$XmlSourceExploderWorkAction
> java.lang.NullPointerException (no error message)
```

This module is an Android library module with some plugins applied to it (`org.jetbrains.kotlin.kapt`, `androidx.navigation.safeargs.kotlin`, `kotlin-parcelize`) like many others in the codebase.

I can't find where this NPE is exactly located in the `XmlSourceExploderWorkAction` (even with the `--stacktrace` option)

**Comment by autonomousapps** [comment]
Is that the entire error message, even when using `--stacktrace`?

**Comment by SimonMarquis** [comment]
Oups, I missed one of the stacktrace causes (buried under Gradle's own causes).

```
Caused by: java.lang.NullPointerException
	at com.autonomousapps.model.AndroidResSource$AttrRef$Companion.attr(Source.kt:139)
	at com.autonomousapps.model.AndroidResSource$AttrRef$Companion.from(Source.kt:109)
	at com.autonomousapps.internal.parse.AndroidResParser.extractAttrsFromResourceXml(explodeAndroidResSource.kt:61)
	at com.autonomousapps.internal.parse.AndroidResParser.<init>(explodeAndroidResSource.kt:45)
	at com.autonomousapps.tasks.XmlSourceExploderTask$XmlSourceExploderWorkAction.execute(XmlSourceExploderTask.kt:123)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)
	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:212)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:187)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.access$700(DefaultConditionalExecutionQueue.java:120)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner$1.run(DefaultConditionalExecutionQueue.java:162)
	at org.gradle.internal.Factories$1.create(Factories.java:31)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:249)
	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:109)
	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:114)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:157)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:126)
	... 2 more
```

And this corresponds to this line:

```kotlin
private fun String.attr(): String = ATTR_REGEX.find(this)!!.groupValues[1]
```

https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/611ac063763b6b712a984832c1ecb3c278ee6336/src/main/kotlin/com/autonomousapps/model/Source.kt

**Comment by SimonMarquis** [comment]
I think I've found what is causing the issue.
Some of the XML files if the corresponding Android module uses `?` like this in a layout:

```xml
<TextView [...] android:text="?" />
```

This character appears red in the IDE with the following message:
> Invalid resource reference - missing resource type 

Though it still builds correctly, and renders in the IDE design panel.

Do you think the plugin should handle this special case (in which case we'll have to update 
the condition `id.startsWith('?')` and replace it directly with the regex), or that it should not?

**Comment by autonomousapps** [comment]
So the issue is [this line](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/611ac063763b6b712a984832c1ecb3c278ee6336/src/main/kotlin/com/autonomousapps/model/Source.kt#L107), which assumes that if the value starts with `"?"`, then it is a reference to another resource. But in your case, it's just a normal string literal. If that's the case, then I think we could update [this block](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/611ac063763b6b712a984832c1ecb3c278ee6336/src/main/kotlin/com/autonomousapps/model/Source.kt#L107-L110) to return `null` when `ATTR_REGEX.find(this) == null`, [here](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/611ac063763b6b712a984832c1ecb3c278ee6336/src/main/kotlin/com/autonomousapps/model/Source.kt#L139).

**Comment by SimonMarquis** [comment]
Could we do something simpler and similar to TYPE_REGEX in the first branch?

```kotlin
        return when {
          TYPE_ATTR.containsMatchIn(id) -> AttrRef(
            type = "attr",
            id = id.attr().replace('.', '_')
          )
          TYPE_REGEX.containsMatchIn(id) -> AttrRef(
            type = id.type(),
            // @drawable/some_drawable => some_drawable
            id = id.substringAfterLast('/').replace('.', '_')
          )
```

**Comment by autonomousapps** [comment]
Honestly regex gives me a splitting headache so I'll need to think on that a bit before answering.

**Comment by SimonMarquis** [comment]
No worries. Maybe we can implement a test harness around all expected values. I can help with that :+1:
