### ISSUE TITLE
Error in `SynthesizeDependenciesWorkAction` when accessing file name with "?" on Windows

### ISSUE THREAD

**Issue by sschuberth** [autonomousapps/dependency-analysis-android-gradle-plugin#889]
**Build scan link**

n/a

**Plugin version**

1.19.0

**Gradle version**

8.1

**(Optional) Android Gradle Plugin (AGP) version**

None (this isn't an Android project).

**`reason` output for bugs relating to incorrect advice**

n/a

**Describe the bug**

Running `./gradlew :plugins:package-managers:python:projectHealth` on https://github.com/oss-review-toolkit/ort *under Windows* gives

```
$ ./gradlew :plugins:package-managers:python:projectHealth

> Configure project :
Building ORT version 85cd638385.

> Task :plugins:package-managers:python-package-manager:synthesizeDependenciesTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':plugins:package-managers:python-package-manager:synthesizeDependenciesTest'.
> A failure occurred while executing com.autonomousapps.tasks.SynthesizeDependenciesTask$SynthesizeDependenciesWorkAction
   > C:\Users\Sebastian\Development\GitHub\oss-review-toolkit\ort\plugins\package-managers\python\build\reports\dependency-analysis\test\dependencies\() -> java.io.File?.json (The filename, directory name, or volume label syntax is incorrect)
```

I guess that's because file names may not contain "?" on Windows / NTFS.

**To Reproduce**

See above.

**Expected behavior**

No exception should be thrown.

**Additional context**

Bottom part of the stacktrace:

```
Caused by: java.io.FileNotFoundException: C:\Users\Sebastian\Development\GitHub\oss-review-toolkit\ort\plugins\package-managers\python\build\reports\dependency-analysis\test\dependencies\() -> java.io.File?.json (The filename, directory name, or volume label syntax is incorrect)
        at okio.Okio__JvmOkioKt.sink(JvmOkio.kt:173)
        at okio.Okio.sink(Unknown Source)
        at okio.Okio__JvmOkioKt.sink$default(JvmOkio.kt:173)
        at okio.Okio.sink$default(Unknown Source)
        at com.autonomousapps.tasks.SynthesizeDependenciesTask$SynthesizeDependenciesWorkAction.execute(SynthesizeDependenciesTask.kt:368)
```

**Comment by sschuberth** [comment]
I just realized this was introduced by our project's upgrade from Kotlin 1.8.10 to 1.8.20, so it's a duplicate of https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/884.
